debug: true
server:
  host: "0.0.0.0"
  port: "9300"

redis:
  host: "192.168.100.233"
  port: "6380"
  passwd: "56grTbvMYaOQ"
  dbnum: 14

mongodb:
  host: "192.168.100.233"
  port: "27020"
  user: "test"
  passwd: "test"
  database: "testrole"

wechat:
  app:
    appid: "wxdc1684c9e82c42b4"
    secret: ""
  xiaochengxu:
    appid: "wxdc1684c9e82c42b4"
    secret: ""
  web:
    appid: "wx233ca74b3d313293"
    secret: ""
    token: ""
    aeskey: ""

phonesms:
  account: ""
  password: ""
  url: "https://106.ihuyi.com/webservice/sms.php?method=Submit"
  debug: true

