debug: true

# 目的是兼容旧有代码
# 新的项目中，不应该打这个补丁
uriprefix: "/sso"

server:
  host: "0.0.0.0"
  port: "9300"

redis:
  host: "192.168.100.233"
  port: "6380"
  passwd: "56grTbvMYaOQ"
  dbnum: 14

mongodb:
  host: "192.168.100.233"
  port: "27020"
  user: "test"
  passwd: "test"
  database: "testrole"

# api token 分为三个级别
# normal - 最低级别调用，仅包含部分 api 调用权限
# high - 高级别，除了极个别权限外，拥有所有的权限
# root - 最高级别，拥有所有的 api 权限
apitoken:
  normal: ""
  high: ""
  root: ""

wechat:
  app:
    appid: "wxdc1684c9e82c42b4"
    secret: ""
  xiaochengxu:
    appid: "wxdc1684c9e82c42b4"
    secret: ""
  web:
    appid: "wx233ca74b3d313293"
    secret: ""
    token: ""
    aeskey: ""

phonesms:
  account: ""
  password: ""
  url: "https://106.ihuyi.com/webservice/sms.php?method=Submit"
  debug: true

